version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/apps/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/scripts/cron"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/apps/api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/apps/post-extraction"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/apps/post-ingestion"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/apps/rec-engine"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/apps/user-extraction"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/apps/shared"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/scripts/legacy-ingestion"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "BryanOwens012"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
